"""
Insight delivery module for sending analysis results to users.

Supports multiple delivery channels, with Telegram as the primary implementation.
"""

import asyncio
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional

from telegram import Bot
from telegram.error import TelegramError

from stock_analyzer.exceptions import DeliveryError
from stock_analyzer.models import DeliveryLog, Insight
from stock_analyzer.storage import Storage


@dataclass
class DeliveryResult:
    """Result of a delivery operation (personal use)."""
    insight_id: int
    channel_id: str  # Channel ID (e.g., @channelname or -1001234567890)
    channel: str  # Delivery method (e.g., "telegram")
    status: str  # "success" or "failed"
    error_message: Optional[str] = None


class DeliveryChannel(ABC):
    """Abstract base class for delivery channels."""

    @abstractmethod
    async def send(self, user_id: str, message: str) -> bool:
        """
        Send message to channel.

        Args:
            user_id: Channel identifier (username or numeric ID)
            message: Message content to send

        Returns:
            True if successful, False otherwise

        Raises:
            DeliveryError: If delivery fails
        """
        pass

    @abstractmethod
    def format_insight(self, insight: Insight) -> str:
        """
        Format insight for this channel.

        Args:
            insight: Insight to format

        Returns:
            Formatted message string
        """
        pass


class TelegramChannel(DeliveryChannel):
    """Telegram delivery channel implementation."""

    def __init__(self, token: str, parse_mode: str = "Markdown"):
        """
        Initialize Telegram channel.

        Args:
            token: Telegram bot token
            parse_mode: Message parse mode (Markdown or HTML)
        """
        self.bot = Bot(token=token)
        self.parse_mode = parse_mode

    async def send(self, user_id: str, message: str) -> bool:
        """
        Send message via Telegram to personal channel.

        Supports channel identifiers:
        - Channel username: @channelname
        - Numeric channel ID: -1001234567890 (for private channels)

        Args:
            user_id: Telegram channel ID (username like @channel or numeric ID)
            message: Message to send

        Returns:
            True if successful

        Raises:
            DeliveryError: If sending fails (invalid ID, permissions, network error)
        """
        try:
            # Convert user_id to int if it's numeric, otherwise use as-is
            chat_id = int(user_id) if user_id.isdigit() or (user_id.startswith('-') and user_id[1:].isdigit()) else user_id

            await self.bot.send_message(
                chat_id=chat_id,
                text=message,
                parse_mode=self.parse_mode
            )
            return True

        except TelegramError as e:
            raise DeliveryError(
                user_id=user_id,
                reason=str(e),
                channel="telegram"
            )
        except Exception as e:
            raise DeliveryError(
                user_id=user_id,
                reason=f"Unexpected error: {str(e)}",
                channel="telegram"
            )

    def format_insight(self, insight: Insight) -> str:
        """
        Format insight for Telegram with Markdown.

        Args:
            insight: Insight to format

        Returns:
            Markdown-formatted message
        """
        # Build message parts
        header = f"📊 *{insight.stock_symbol}* Stock Analysis"
        date_str = f"📅 {insight.analysis_date.strftime('%B %d, %Y')}"

        # Confidence indicator
        confidence_emoji = {
            "high": "🟢",
            "medium": "🟡",
            "low": "🔴"
        }
        confidence = f"{confidence_emoji.get(insight.confidence_level, '⚪')} Confidence: {insight.confidence_level.upper()}"

        # Summary
        summary = f"*Summary:*\n{insight.summary}"

        # Trend analysis (if available)
        trend = ""
        if insight.trend_analysis:
            trend = f"\n\n*Trend Analysis:*\n{insight.trend_analysis}"

        # Risk factors
        risks = ""
        if insight.risk_factors:
            risks = "\n\n*⚠️ Risk Factors:*"
            for risk in insight.risk_factors:
                risks += f"\n• {risk}"

        # Opportunities
        opportunities = ""
        if insight.opportunities:
            opportunities = "\n\n*💡 Opportunities:*"
            for opp in insight.opportunities:
                opportunities += f"\n• {opp}"

        # Footer
        footer = f"\n\n_Analysis generated by AlphaAgent_"

        # Combine all parts
        message = f"{header}\n{date_str}\n{confidence}\n\n{summary}{trend}{risks}{opportunities}{footer}"

        # Telegram has a 4096 character limit
        if len(message) > 4096:
            message = message[:4093] + "..."

        return message


class InsightDeliverer:
    """Manages delivery of insights to users via multiple channels."""

    def __init__(
        self,
        storage: Storage,
        telegram_token: Optional[str] = None
    ):
        """
        Initialize deliverer.

        Args:
            storage: Storage instance for logging
            telegram_token: Telegram bot token (required for Telegram delivery)
        """
        self.storage = storage
        self.channels = {}

        # Initialize Telegram channel if token provided
        if telegram_token:
            self.channels["telegram"] = TelegramChannel(telegram_token)

    def add_channel(self, name: str, channel: DeliveryChannel):
        """
        Add a delivery channel.

        Args:
            name: Channel name (e.g., "telegram", "email")
            channel: Channel implementation
        """
        self.channels[name] = channel

    async def deliver_insight(
        self,
        insight: Insight,
        user_id: str,
        channel: str = "telegram"
    ) -> DeliveryResult:
        """
        Deliver insight to personal channel (internal method).

        Args:
            insight: Insight to deliver
            user_id: Channel identifier (username or numeric ID)
            channel: Delivery channel name (default: telegram)

        Returns:
            DeliveryResult with status

        Raises:
            DeliveryError: If channel not found or delivery fails
        """
        if channel not in self.channels:
            raise DeliveryError(
                user_id=user_id,
                reason=f"Channel '{channel}' not configured",
                channel=channel
            )

        delivery_channel = self.channels[channel]

        try:
            # Format message
            message = delivery_channel.format_insight(insight)

            # Send message
            await delivery_channel.send(user_id, message)

            # Log successful delivery (user_id treated as channel_id for personal use)
            self._log_delivery(
                insight_id=insight.id,
                channel_id=user_id,
                channel=channel,
                status="success"
            )

            return DeliveryResult(
                insight_id=insight.id,
                channel_id=user_id,
                channel=channel,
                status="success"
            )

        except DeliveryError as e:
            # Log failed delivery
            self._log_delivery(
                insight_id=insight.id,
                channel_id=user_id,
                channel=channel,
                status="failed",
                error_message=str(e)
            )

            return DeliveryResult(
                insight_id=insight.id,
                channel_id=user_id,
                channel=channel,
                status="failed",
                error_message=str(e)
            )

    def _log_delivery(
        self,
        insight_id: int,
        channel_id: str,
        channel: str,
        status: str,
        error_message: Optional[str] = None
    ):
        """
        Log delivery to storage (personal use).

        Args:
            insight_id: Insight ID that was delivered
            channel_id: Channel ID that received the delivery (@channelname or numeric ID)
            channel: Delivery channel used
            status: Delivery status ("success" or "failed")
            error_message: Error message if failed
        """
        log = DeliveryLog(
            insight_id=insight_id,
            channel_id=channel_id,
            delivery_method=channel,
            delivery_status=status,
            error_message=error_message,
            delivered_at=datetime.utcnow()
        )
        self.storage.save_delivery_log(log)

    async def deliver_to_channel(
        self,
        insight: Insight,
        channel_id: str,
        channel: str = "telegram"
    ) -> DeliveryResult:
        """
        Deliver insight to a personal Telegram channel (personal use).

        Args:
            insight: Insight to deliver
            channel_id: Telegram channel ID (@channelname or numeric ID like -1001234567890)
            channel: Delivery channel name (default: "telegram")

        Returns:
            DeliveryResult with delivery status

        Raises:
            DeliveryError: If channel not configured
        """
        if channel not in self.channels:
            return DeliveryResult(
                insight_id=insight.id or 0,
                channel_id=channel_id,
                channel=channel,
                status="failed",
                error_message=f"Channel '{channel}' not configured"
            )

        delivery_channel = self.channels[channel]

        try:
            # Format message
            message = delivery_channel.format_insight(insight)

            # Send to channel
            await delivery_channel.send(channel_id, message)

            # Log successful delivery
            self._log_delivery(
                insight_id=insight.id or 0,
                channel_id=channel_id,
                channel=channel,
                status="success",
                error_message=None
            )

            return DeliveryResult(
                insight_id=insight.id or 0,
                channel_id=channel_id,
                channel=channel,
                status="success",
                error_message=None
            )

        except DeliveryError as e:
            # Log failed delivery
            error_msg = e.reason
            self._log_delivery(
                insight_id=insight.id or 0,
                channel_id=channel_id,
                channel=channel,
                status="failed",
                error_message=error_msg
            )

            return DeliveryResult(
                insight_id=insight.id or 0,
                channel_id=channel_id,
                channel=channel,
                status="failed",
                error_message=error_msg
            )

        except Exception as e:
            # Log unexpected failure
            error_msg = f"Unexpected error: {str(e)}"
            self._log_delivery(
                insight_id=insight.id or 0,
                channel_id=channel_id,
                channel=channel,
                status="failed",
                error_message=error_msg
            )

            return DeliveryResult(
                insight_id=insight.id or 0,
                channel_id=channel_id,
                channel=channel,
                status="failed",
                error_message=error_msg
            )
